### ISSUE TITLE
Invoke not concurrency safe

### ISSUE THREAD

**Issue by njspok** [uber-go/dig#241]
Run simple test complete panic with stack trace (maybe test run several times)
```go
package app

import (
	"testing"
	"time"

	"go.uber.org/dig"
)

type comp1 struct{}

func TestDI(t *testing.T) {
	di := dig.New()

	_ = di.Provide(func() *comp1 {
		return &comp1{}
	})

	for i := 0; i < 10000; i++ {
		go func() {
			_ = di.Invoke(func(c *comp1) {
				time.Sleep(1 * time.Millisecond)
			})
		}()
	}
}

```

Stack trace
```
goroutine 1767 [semacquire]:
sync.runtime_SemacquireMutex(0xe90f24, 0x0)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xe90f20)
	/usr/local/go/src/sync/mutex.go:134 +0xff
sync.(*Map).Load(0xe90f20, 0x967e60, 0xc001b05608, 0x0, 0x0, 0x0)
	/usr/local/go/src/sync/map.go:106 +0x178
reflect.funcLayout(0x907e20, 0x0, 0x40f0e6, 0xc001a0a7b0, 0xc001a0a760, 0x444a87, 0x10)
	/usr/local/go/src/reflect/type.go:3053 +0xa2
reflect.Value.call(0x907e20, 0xa493d0, 0x13, 0x9db09b, 0x4, 0xeaf048, 0x0, 0x0, 0x964080, 0x9b1001, ...)
	/usr/local/go/src/reflect/value.go:405 +0x35e
reflect.Value.Call(0x907e20, 0xa493d0, 0x13, 0xeaf048, 0x0, 0x0, 0xc000329b80, 0xeaf048, 0x0)
	/usr/local/go/src/reflect/value.go:308 +0xa4
go.uber.org/dig.(*node).Call(0xc0003cb540, 0xabeb20, 0xc000329b80, 0xac44c0, 0x8fba40)
	/home/oleg/Projects/go-workspace/pkg/mod/go.uber.org/dig@v1.7.0/dig.go:665 +0x229
go.uber.org/dig.paramSingle.Build(0x0, 0x0, 0x0, 0xac44c0, 0x8fba40, 0xabeb20, 0xc000329b80, 0x444a87, 0x20, 0x9d9100, ...)
	/home/oleg/Projects/go-workspace/pkg/mod/go.uber.org/dig@v1.7.0/param.go:245 +0x359
go.uber.org/dig.paramList.BuildList(0xac44c0, 0x90a0a0, 0xc001a06940, 0x1, 0x1, 0xabeb20, 0xc000329b80, 0x0, 0x0, 0x0, ...)
	/home/oleg/Projects/go-workspace/pkg/mod/go.uber.org/dig@v1.7.0/param.go:201 +0xc4
go.uber.org/dig.(*Container).Invoke(0xc000329b80, 0x90a0a0, 0xa493d8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/oleg/Projects/go-workspace/pkg/mod/go.uber.org/dig@v1.7.0/dig.go:389 +0x2d3
stash.sima-land.ru/pac/go-mimicro/app.TestDI.func2(0xc000329b80)
	/home/oleg/Projects/go-workspace/src/stash.sima-land.ru/pac/go-mimicro/app/app_test.go:21 +0x54
created by stash.sima-land.ru/pac/go-mimicro/app.TestDI
	/home/oleg/Projects/go-workspace/src/stash.sima-land.ru/pac/go-mimicro/app/app_test.go:20 +0x9d
```
Indicates about not safe concurrency, how fix it?

**Comment by glibsm** [comment]
`dig` has no goroutine safety. I thought that it was clearly stated in the docs, but after taking a look just now there doesn't seem to be a mention of it. Would be good to add for clarity.

If you want concurrent usage, you should manage your own sync mutex for access to the dig container. However, in the example provided (I assume somewhat contrived to illustrate a point) you should `Invoke` first and then just pass the object to your goroutines rather than asking `dig` to deal with the caching (it will never re-instantiate).
